version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony/
        networks:
            - symfony
        container_name: case-php
    nginx:
        build:
            context: ./nginx
        ports:
            - 80:80
        volumes:
          - ../:/var/www/symfony/
        networks:
            - symfony
        env_file:
            - .env.nginx.local
        extra_hosts:
            - "host.docker.internal:0.0.0.0"
    rabbitmq:
        image: rabbitmq:management
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: dev
            RABBITMQ_DEFAULT_PASS: dev
        networks:
            - symfony
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
